language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "node"
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
install:
  - CC=gcc-4.9 CXX=g++-4.9 npm install
  - npm run fetch-test-suites
script:
  - if [ "x$BUNDLER" = "x" ]; then npm run test; fi
  - if [ "x$BUNDLER" != "x" ]; then npm run test-karma; fi
# only run karma tests for one node version
matrix:
  include:
  - node_js: "6"
    env: BUNDLER=webpack
#  - node_js: "6"
#    env: BUNDLER=browserify
notifications:
  email:
    on_success: change
    on_failure: change
