language: node_js
node_js:
  - "0.10"
  - "0.12"
  - iojs
sudo: false
# download test suite and run tests... submodule? meta testing project with
# all of the reference implementations?
script: 
  - git clone https://github.com/json-ld/json-ld.org.git _json-ld.org
  - make test JSONLD_TEST_SUITE=./_json-ld.org/test-suite
notifications:
  email:
    on_success: change
    on_failure: change
